/*
 * Mock dataset usado solo cuando Supabase no esta configurado o no responde.
 * Cada articulo declara distribution_scope + source_country + target_countries
 * para validar la logica de filtrado editorial sin DB.
 *
 * Convencion editorial:
 *  - Titulares en estilo sarcastico/satirico inspirados en temas reales de
 *    actualidad (inflacion, transporte, IA, futbol, elecciones, vivienda,
 *    clima, economia, tecnologia, seguridad, migracion).
 *  - NO se inventan cifras, citas, ni nombres propios atribuibles. Se evita
 *    cualquier hecho concreto que pudiera leerse como dato real falso.
 *  - El kicker incluye scope (GLOBAL/LOCAL) + pais para que el preview
 *    muestre claramente como funciona el ruteo multi-pais.
 */

import { Article } from './supabase';

type Mock = Omit<Article, 'sort_order' | 'active'> & { sort_order?: number; active?: boolean };

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

const base = (m: Mock): Article => ({
  sort_order: 0,
  active: true,
  ...m,
});

export const MOCK_ARTICLES: Article[] = [
  // ============ GLOBALES (visibles en todas las ediciones) ============
  base({
    id: 'g1',
    title: 'NUEVA IA PROMETE REEMPLAZAR A TU JEFE: EL UNICO PROBLEMA ES QUE TAMBIEN TE QUIERE REEMPLAZAR A VOS',
    excerpt: 'El modelo, entrenado con mails pasivo-agresivos, ya supera a humanos en pedir informes los viernes a las 18:00. Expertos recomiendan no entrar en panico, pero entrar igual.',
    image_url: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'GLOBAL · TECNOLOGIA',
    kicker_color: '#cc0000',
    size: 'large',
    section: 'tragedias',
    views: '3.2M',
    comments: 847,
    published_at: hoursAgo(1),
    featured: true,
    distribution_scope: 'global',
    source_country: 'WORLD',
    target_countries: [],
  }),
  base({
    id: 'g2',
    title: 'CRISIS CLIMATICA: METEOROLOGOS PIDEN INVENTAR UNA ESTACION NUEVA ENTRE VERANO Y APOCALIPSIS',
    excerpt: 'La propuesta busca dar nombre formal a esos meses en que el aire acondicionado es un derecho humano.',
    image_url: 'https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'GLOBAL · CLIMA',
    kicker_color: '#e65c00',
    size: 'small',
    section: 'tragedias',
    views: '1.8M',
    comments: 412,
    published_at: hoursAgo(2),
    featured: false,
    distribution_scope: 'global',
    source_country: 'WORLD',
    target_countries: [],
  }),
  base({
    id: 'g3',
    title: 'ECONOMIA MUNDIAL ANUNCIA QUE LA INFLACION "BAJO": SIGUE SUBIENDO, PERO MAS DESPACIO',
    excerpt: 'Bancos centrales celebran el matiz. Consumidores, no tanto.',
    image_url: 'https://images.pexels.com/photos/210607/pexels-photo-210607.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'GLOBAL · ECONOMIA',
    kicker_color: '#e65c00',
    size: 'small',
    section: 'catastrofes',
    views: '1.4M',
    comments: 521,
    published_at: hoursAgo(5),
    featured: false,
    distribution_scope: 'global',
    source_country: 'WORLD',
    target_countries: [],
  }),
  base({
    id: 'g4',
    title: 'CUMBRE INTERNACIONAL CONCLUYE CON UN COMUNICADO QUE NO DICE NADA, FIRMADO POR TODOS',
    excerpt: 'Diplomaticos lo describen como un exito historico de redaccion ambigua.',
    image_url: 'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'GLOBAL · POLITICA',
    kicker_color: '#cc0000',
    size: 'small',
    section: 'tragedias',
    views: '1.1M',
    comments: 318,
    published_at: hoursAgo(6),
    featured: false,
    distribution_scope: 'global',
    source_country: 'WORLD',
    target_countries: [],
  }),

  // ============ LOCALES (uno por pais soportado) ============
  base({
    id: 'l-ar',
    title: 'INFLACION ARGENTINA ALCANZA NIVEL ESPIRITUAL: YA NO SE MIDE, SE SIENTE',
    excerpt: 'Economistas debaten si el supermercado deberia tener cura de almas. El dolar paralelo pide ser tratado como persona.',
    image_url: 'https://images.pexels.com/photos/210600/pexels-photo-210600.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'LOCAL · AR',
    kicker_color: '#75aadb',
    size: 'small',
    section: 'tragedias',
    views: '2.1M',
    comments: 633,
    published_at: hoursAgo(3),
    featured: false,
    distribution_scope: 'local',
    source_country: 'AR',
    country: 'AR',
  }),
  base({
    id: 'l-mx',
    title: 'CDMX: TRAFICO PROPONE SER RECONOCIDO COMO ECOSISTEMA CON FAUNA PROPIA',
    excerpt: 'Biologos ya estudian la migracion del microbusero y los habitos del repartidor en moto. El Periferico, candidato a patrimonio emocional.',
    image_url: 'https://images.pexels.com/photos/1004409/pexels-photo-1004409.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'LOCAL · MX',
    kicker_color: '#006847',
    size: 'small',
    section: 'tragedias',
    views: '980K',
    comments: 289,
    published_at: hoursAgo(4),
    featured: false,
    distribution_scope: 'local',
    source_country: 'MX',
    country: 'MX',
  }),
  base({
    id: 'l-es',
    title: 'CRISIS DE VIVIENDA EN ESPAÑA: ALQUILAR UN PISO YA REQUIERE AVALISTA, NOMINA Y PADRINOS DE BAUTISMO',
    excerpt: 'Inmobiliarias ofrecen "estudios" de 18 metros con vistas a otro estudio de 18 metros. La okupacion debate si rebautizarse como "coliving alternativo".',
    image_url: 'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'LOCAL · ES',
    kicker_color: '#aa151b',
    size: 'small',
    section: 'tragedias',
    views: '1.1M',
    comments: 322,
    published_at: hoursAgo(4),
    featured: false,
    distribution_scope: 'local',
    source_country: 'ES',
    country: 'ES',
  }),
  base({
    id: 'l-co',
    title: 'BOGOTA: TRANCON EN LA AUTOPISTA NORTE PIDE SER INCORPORADO COMO BARRIO',
    excerpt: 'Vecinos ya pagan administracion y servicios publicos sin moverse del carril. Transmilenio observa con envidia.',
    image_url: 'https://images.pexels.com/photos/210182/pexels-photo-210182.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'LOCAL · CO',
    kicker_color: '#fcd116',
    size: 'small',
    section: 'tragedias',
    views: '870K',
    comments: 245,
    published_at: hoursAgo(5),
    featured: false,
    distribution_scope: 'local',
    source_country: 'CO',
    country: 'CO',
  }),
  base({
    id: 'l-cl',
    title: 'CHILE REDEFINE EL "AL TIRO": AHORA INCLUYE TODO EL RANGO ENTRE 5 MINUTOS Y NUNCA',
    excerpt: 'Linguistas celebran la flexibilidad. Usuarios del transporte publico, menos.',
    image_url: 'https://images.pexels.com/photos/1426044/pexels-photo-1426044.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'LOCAL · CL',
    kicker_color: '#0039a6',
    size: 'small',
    section: 'tragedias',
    views: '650K',
    comments: 187,
    published_at: hoursAgo(6),
    featured: false,
    distribution_scope: 'local',
    source_country: 'CL',
    country: 'CL',
  }),
  base({
    id: 'l-pe',
    title: 'LIMA DECLARA EMERGENCIA SENTIMENTAL POR LA NEBLINA: "NO ES LLUVIA, ES UN ESTADO DE ANIMO"',
    excerpt: 'El Ministerio del Ambiente confirma que la garua es, oficialmente, una forma de pasivo-agresividad meteorologica.',
    image_url: 'https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'LOCAL · PE',
    kicker_color: '#d91023',
    size: 'small',
    section: 'tragedias',
    views: '540K',
    comments: 152,
    published_at: hoursAgo(7),
    featured: false,
    distribution_scope: 'local',
    source_country: 'PE',
    country: 'PE',
  }),
  base({
    id: 'l-ve',
    title: 'VENEZUELA INAUGURA NUEVA UNIDAD MONETARIA: EL "POR LAS DUDAS"',
    excerpt: 'Los venezolanos cotizan en dolares, en bolivares y en favores. Economistas sugieren incluir el trueque como tercera reserva.',
    image_url: 'https://images.pexels.com/photos/259027/pexels-photo-259027.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'LOCAL · VE',
    kicker_color: '#cf142b',
    size: 'small',
    section: 'tragedias',
    views: '420K',
    comments: 118,
    published_at: hoursAgo(8),
    featured: false,
    distribution_scope: 'local',
    source_country: 'VE',
    country: 'VE',
  }),
  base({
    id: 'l-us',
    title: 'EEUU: ELECCIONES DE MEDIO TERMINO TAMBIEN SERAN DE MEDIO ATAQUE DE PANICO',
    excerpt: 'Encuestadores piden que se les permita votar dos veces para compensar el estres. Las redes sociales ya estan ardiendo, como cada cuatro anios.',
    image_url: 'https://images.pexels.com/photos/8828687/pexels-photo-8828687.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'LOCAL · US',
    kicker_color: '#3c3b6e',
    size: 'small',
    section: 'tragedias',
    views: '1.6M',
    comments: 489,
    published_at: hoursAgo(3),
    featured: false,
    distribution_scope: 'local',
    source_country: 'US',
    country: 'US',
  }),
  base({
    id: 'l-ca',
    title: 'CENTROAMERICA REPORTA QUE EL CLIMA SOLO TIENE DOS MODOS: HUMEDO Y MAS HUMEDO',
    excerpt: 'Aerolineas ya incluyen el sudor del pasajero como equipaje de mano. El ventilador es declarado patrimonio cultural.',
    image_url: 'https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'LOCAL · CA',
    kicker_color: '#009b3a',
    size: 'small',
    section: 'tragedias',
    views: '360K',
    comments: 94,
    published_at: hoursAgo(9),
    featured: false,
    distribution_scope: 'local',
    source_country: 'CA',
    country: 'CA',
  }),

  // ============ GLOBAL CON TARGETS (audiencias acotadas) ============
  base({
    id: 'g-targeted',
    title: 'AR Y MX EMPATAN EN EL "CAMPEONATO DE CREATIVIDAD FISCAL": NUEVOS IMPUESTOS POR INSPIRACION DIVINA',
    excerpt: 'Tributaristas piden que se reconozca a Hacienda como expresion artistica. Otros paises observan con admiracion y temor.',
    image_url: 'https://images.pexels.com/photos/210600/pexels-photo-210600.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'GLOBAL · AR/MX',
    kicker_color: '#cc0000',
    size: 'small',
    section: 'tragedias',
    views: '760K',
    comments: 198,
    published_at: hoursAgo(7),
    featured: false,
    distribution_scope: 'global',
    source_country: 'AR',
    target_countries: ['AR', 'MX'],
  }),
  base({
    id: 'g-futbol',
    title: 'FUTBOL SUDAMERICANO: HINCHAS PIDEN QUE EL VAR REVISE TAMBIEN SUS PROPIAS DECISIONES DE VIDA',
    excerpt: 'Psicologos deportivos lo consideran "razonable". Los arbitros, en cambio, ya pidieron escolta.',
    image_url: 'https://images.pexels.com/photos/47730/the-ball-stadion-football-the-pitch-47730.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'GLOBAL · AR/CO/CL/PE',
    kicker_color: '#006847',
    size: 'small',
    section: 'tragedias',
    views: '1.3M',
    comments: 402,
    published_at: hoursAgo(5),
    featured: false,
    distribution_scope: 'global',
    source_country: 'AR',
    target_countries: ['AR', 'CO', 'CL', 'PE'],
  }),
  base({
    id: 'g-migracion',
    title: 'MIGRACION EN LAS AMERICAS: LA UNICA FRONTERA QUE NO SE CRUZA ES LA DEL SENTIDO COMUN POLITICO',
    excerpt: 'Analistas advierten que el debate publico migra mas rapido que las personas.',
    image_url: 'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'GLOBAL · US/MX/VE',
    kicker_color: '#cc0000',
    size: 'small',
    section: 'tragedias',
    views: '910K',
    comments: 287,
    published_at: hoursAgo(4),
    featured: false,
    distribution_scope: 'global',
    source_country: 'US',
    target_countries: ['US', 'MX', 'VE'],
  }),
  base({
    id: 'g-seguridad',
    title: 'CIBERSEGURIDAD: USUARIOS DESCUBREN QUE "123456" SIGUE SIENDO LA CONTRASEÑA MAS POPULAR Y NO PIENSAN CAMBIARLA',
    excerpt: 'Expertos llevan dos decadas pidiendo lo mismo. La humanidad responde con un encogimiento de hombros colectivo.',
    image_url: 'https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'GLOBAL · SEGURIDAD',
    kicker_color: '#e65c00',
    size: 'small',
    section: 'tragedias',
    views: '1.2M',
    comments: 356,
    published_at: hoursAgo(6),
    featured: false,
    distribution_scope: 'global',
    source_country: 'WORLD',
    target_countries: [],
  }),
];
