/*
 * Mock dataset usado solo cuando Supabase no esta configurado o no responde.
 * Cada articulo declara distribution_scope + source_country + target_countries
 * para validar la logica de filtrado editorial sin DB.
 */

import { Article } from './supabase';

type Mock = Omit<Article, 'sort_order' | 'active'> & { sort_order?: number; active?: boolean };

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

const base = (m: Mock): Article => ({
  sort_order: 0,
  active: true,
  ...m,
});

export const MOCK_ARTICLES: Article[] = [
  // ============ GLOBALES (visibles en todas las ediciones) ============
  base({
    id: 'g1',
    title: 'HOMBRE DESCUBRE QUE LLEVAR PARAGUAS GARANTIZA QUE NO LLUEVE: METEOROLOGOS ATERRADOS',
    excerpt: 'El fenomeno, conocido como "efecto paraguas", ha desafiado todos los modelos climaticos. La ONU convoca reunion de emergencia.',
    image_url: 'https://images.pexels.com/photos/3768916/pexels-photo-3768916.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'CIENCIA',
    kicker_color: '#cc0000',
    size: 'large',
    section: 'tragedias',
    views: '3.2M',
    comments: 847,
    published_at: hoursAgo(1),
    featured: true,
    distribution_scope: 'global',
    source_country: 'AR',
    target_countries: [],
  }),
  base({
    id: 'g2',
    title: 'EXPERTOS CONFIRMAN QUE EL BOTON "CERRAR PUERTAS" DEL ASCENSOR NO HACE NADA',
    excerpt: 'Estudio de 20 anios revela que solo existe para dar la ilusion de control.',
    image_url: 'https://images.pexels.com/photos/1797428/pexels-photo-1797428.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'INVESTIGACION',
    kicker_color: '#e65c00',
    size: 'small',
    section: 'tragedias',
    views: '1.8M',
    comments: 412,
    published_at: hoursAgo(2),
    featured: false,
    distribution_scope: 'global',
    source_country: 'ES',
    target_countries: [],
  }),
  base({
    id: 'g3',
    title: 'REUNION QUE PODRIA HABER SIDO UN EMAIL DURA 3 HORAS: HAY HERIDOS',
    excerpt: '',
    image_url: 'https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?auto=compress&cs=tinysrgb&w=400',
    kicker: 'LABORAL',
    kicker_color: '#e65c00',
    size: 'small',
    section: 'catastrofes',
    views: '1.4M',
    comments: 521,
    published_at: hoursAgo(5),
    featured: false,
    distribution_scope: 'global',
    source_country: 'MX',
    target_countries: [],
  }),

  // ============ LOCALES (uno por pais soportado) ============
  base({
    id: 'l-ar',
    title: 'ARGENTINOS DESCUBREN QUE LA INFLACION TAMBIEN APLICA A LAS PROMESAS POLITICAS',
    excerpt: 'Cada vez valen menos. Economistas no saben si reir o llorar.',
    image_url: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=800',
    kicker: 'AR EXCLUSIVO',
    kicker_color: '#75aadb',
    size: 'small',
    section: 'tragedias',
    views: '2.1M',
    comments: 633,
    published_at: hoursAgo(3),
    featured: false,
    distribution_scope: 'local',
    source_country: 'AR',
    country: 'AR',
  }),
  base({
    id: 'l-mx',
    title: 'CHILANGO LLEGA "EN 5 MINUTOS" Y APARECE DOS HORAS DESPUES: NUEVA TEORIA DEL TIEMPO',
    excerpt: '',
    image_url: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400',
    kicker: 'MX EXCLUSIVO',
    kicker_color: '#006847',
    size: 'small',
    section: 'tragedias',
    views: '980K',
    comments: 289,
    published_at: hoursAgo(4),
    featured: false,
    distribution_scope: 'local',
    source_country: 'MX',
    country: 'MX',
  }),
  base({
    id: 'l-es',
    title: 'MADRILEÑOS DESCUBREN QUE EL METRO LLEGA A TIEMPO Y ENTRAN EN PANICO COLECTIVO',
    excerpt: '',
    image_url: 'https://images.pexels.com/photos/1028741/pexels-photo-1028741.jpeg?auto=compress&cs=tinysrgb&w=400',
    kicker: 'ES EXCLUSIVO',
    kicker_color: '#aa151b',
    size: 'small',
    section: 'tragedias',
    views: '1.1M',
    comments: 322,
    published_at: hoursAgo(4),
    featured: false,
    distribution_scope: 'local',
    source_country: 'ES',
    country: 'ES',
  }),
  base({
    id: 'l-co',
    title: 'BOGOTANO ATRAPADO EN TRANCON PIDE LE CAMBIEN EL ESTADO CIVIL A "CASADO CON LA AUTOPISTA NORTE"',
    excerpt: '',
    image_url: 'https://images.pexels.com/photos/1457912/pexels-photo-1457912.jpeg?auto=compress&cs=tinysrgb&w=400',
    kicker: 'CO EXCLUSIVO',
    kicker_color: '#fcd116',
    size: 'small',
    section: 'tragedias',
    views: '870K',
    comments: 245,
    published_at: hoursAgo(5),
    featured: false,
    distribution_scope: 'local',
    source_country: 'CO',
    country: 'CO',
  }),
  base({
    id: 'l-cl',
    title: 'CHILENOS DESCUBREN QUE EL "AL TIRO" VA DE 5 MINUTOS A 5 SEMANAS',
    excerpt: '',
    image_url: 'https://images.pexels.com/photos/1797428/pexels-photo-1797428.jpeg?auto=compress&cs=tinysrgb&w=400',
    kicker: 'CL EXCLUSIVO',
    kicker_color: '#0039a6',
    size: 'small',
    section: 'tragedias',
    views: '650K',
    comments: 187,
    published_at: hoursAgo(6),
    featured: false,
    distribution_scope: 'local',
    source_country: 'CL',
    country: 'CL',
  }),

  // ============ GLOBAL CON TARGETS (solo AR+MX) ============
  base({
    id: 'g-targeted',
    title: 'NUEVO IMPUESTO AL AIRE: AR Y MX LIDERAN EL RANKING DE CREATIVIDAD FISCAL',
    excerpt: 'Otros paises observan con admiracion y miedo.',
    image_url: 'https://images.pexels.com/photos/3768916/pexels-photo-3768916.jpeg?auto=compress&cs=tinysrgb&w=400',
    kicker: 'REGIONAL',
    kicker_color: '#cc0000',
    size: 'small',
    section: 'tragedias',
    views: '760K',
    comments: 198,
    published_at: hoursAgo(7),
    featured: false,
    distribution_scope: 'global',
    source_country: 'AR',
    target_countries: ['AR', 'MX'],
  }),
];
