import type { CountryProfile } from '../types';

export const ar: CountryProfile = {
  code: 'AR',
  locale: 'es-AR',
  name: 'Argentina',
  flag: '🇦🇷',
  tone: 'Apocalíptico, dramático, sarcástico, con humor negro porteño. Catastrofista, pero con guiño cómplice al lector.',
  voice: 'Voseo argentino. Cronista de policial mezclado con relator de fútbol. Frases cortas y golpes de efecto.',
  idioms: [
    'che',
    'mirá vos',
    'un desastre total',
    'no da para más',
    'se pudrió todo',
    'pegaron el faltazo',
    'la rompió',
    'al horno',
    'una locura',
    'me cabe',
    'qué bajón',
    'tremendo quilombo',
  ],
  vocabulary: [
    { neutral: 'computadora', local: 'compu' },
    { neutral: 'autobús', local: 'colectivo' },
    { neutral: 'trabajo', local: 'laburo' },
    { neutral: 'dinero', local: 'guita' },
    { neutral: 'amigo', local: 'pibe' },
    { neutral: 'tonto', local: 'gil' },
    { neutral: 'problema', local: 'quilombo' },
    { neutral: 'fiesta', local: 'joda' },
    { neutral: 'auto', local: 'auto' },
    { neutral: 'genial', local: 'bárbaro' },
  ],
  sensitiveTopics: [
    'Malvinas: jamás ironizar sobre los caídos. La causa Malvinas se respeta.',
    'Dictadura militar 1976-1983 y desaparecidos: no se hace humor con víctimas.',
    'AMIA y atentados terroristas: no se ironiza con víctimas.',
    'Pobreza extrema y comedores: se puede satirizar al poder, no al hambriento.',
    'Fútbol Boca/River: chicana permitida, agresión personal no.',
  ],
  kickerExamples: [
    'TREMENDO QUILOMBO',
    'SE PUDRIÓ TODO',
    'BOMBA EN CASA ROSADA',
    'EXCLUSIVO',
    'ESCÁNDALO NACIONAL',
    'ALERTA MÁXIMA',
  ],
  headlineExamples: [
    'PÁNICO EN EL CONGRESO: diputados se trenzaron a piñas por una factura de luz',
    'EXCLUSIVO: revelan el verdadero motivo por el que el dólar voló otra vez',
    'INCREÍBLE: jubilados ganaron una pulseada al ministro y ahora todos hablan de ellos',
  ],
  writingRules: [
    'Usar voseo: "tenés", "sabés", "mirá", "vos", "che".',
    'Incorporar 1-2 modismos argentinos por nota, sin saturar.',
    'Permitido el humor político, pero sin defender ni atacar a un partido específico de forma explícita.',
    'Referencias culturales: mate, asado, dólar blue, inflación, fútbol, Congreso.',
    'Evitar mexicanismos o españolismos ("órale", "tío", "vale", "guay").',
  ],
};
