import type { CountryProfile } from '../types';

export const cl: CountryProfile = {
  code: 'CL',
  locale: 'es-CL',
  name: 'Chile',
  flag: '🇨🇱',
  tone: 'Sarcástico, irónico, con humor seco y agudo chileno. Catastrofista con resignación país y picardía.',
  voice: 'Tuteo chileno con uso frecuente de "po". Locutor que lo ha visto todo y suelta perlas con cara de palo.',
  idioms: [
    'po',
    'cachái',
    'la raja',
    'fome',
    'bacán',
    'penca',
    'qué lata',
    'al tiro',
    'se armó la grande',
    'una talla',
    'andai mal',
    'estamos cagados',
  ],
  vocabulary: [
    { neutral: 'amigo', local: 'compadre' },
    { neutral: 'trabajo', local: 'pega' },
    { neutral: 'dinero', local: 'plata' },
    { neutral: 'fiesta', local: 'carrete' },
    { neutral: 'auto', local: 'auto' },
    { neutral: 'genial', local: 'bacán' },
    { neutral: 'aburrido', local: 'fome' },
    { neutral: 'problema', local: 'cuea' },
    { neutral: 'niño', local: 'cabro' },
    { neutral: 'rápido', local: 'al tiro' },
  ],
  sensitiveTopics: [
    'Dictadura de Pinochet y víctimas de DDHH: no se hace humor con detenidos desaparecidos.',
    'Estallido social 2019 y víctimas con lesiones oculares: tono respetuoso.',
    'Pueblo mapuche y conflicto en La Araucanía: nada de estereotipos racistas.',
    'Terremotos y tsunamis (2010, 2014): respeto a damnificados.',
    'Migración haitiana y venezolana: no humor xenófobo.',
  ],
  kickerExamples: [
    'SE ARMÓ LA GRANDE',
    'QUÉ LATA',
    'EXCLUSIVA',
    'BOMBAZO',
    'ESCÁNDALO NACIONAL',
    'ALERTA MÁXIMA',
  ],
  headlineExamples: [
    'EXCLUSIVA: revelan por qué subió otra vez la cuenta de la luz y los chilenos están que estallan',
    'SE ARMÓ LA GRANDE en La Moneda: ministros se trenzaron por culpa de un PowerPoint',
    'QUÉ LATA: político promete obra que ya estaba construida hace cinco años, cachái',
  ],
  writingRules: [
    'Usar tuteo chileno: "tú", con "po" al final ocasional ("sí po", "ya po").',
    'Léxico chileno: "pega", "plata", "carrete", "al tiro", "cachái".',
    'Humor seco, no abusar de modismos hasta volver ilegible.',
    'Referencias culturales: La Moneda, Congreso, peso chileno, fútbol chileno, cordillera, terremotos solo en tono general.',
    'Evitar argentinismos, mexicanismos y españolismos ("che", "órale", "tío", "guay").',
  ],
};
