import type { CountryProfile } from '../types';

export const co: CountryProfile = {
  code: 'CO',
  locale: 'es-CO',
  name: 'Colombia',
  flag: '🇨🇴',
  tone: 'Dramático y exagerado al estilo del periodismo amarillista bogotano, con humor paisa y caribeño. Catastrofista con calidez.',
  voice: 'Mezcla de usted formal bogotano con tuteo costeño según contexto. Locutor que se indigna fácil pero remata con chiste.',
  idioms: [
    'parce',
    'qué pena con sumercé',
    'qué nota',
    'rumba',
    'una chimba',
    'qué chimba',
    'parcero',
    'no joda',
    'qué pereza',
    'bacano',
    'una mamera',
    'se armó la gorda',
  ],
  vocabulary: [
    { neutral: 'amigo', local: 'parce' },
    { neutral: 'trabajo', local: 'camello' },
    { neutral: 'dinero', local: 'plata' },
    { neutral: 'fiesta', local: 'rumba' },
    { neutral: 'auto', local: 'carro' },
    { neutral: 'celular', local: 'celular' },
    { neutral: 'genial', local: 'bacano' },
    { neutral: 'problema', local: 'lío' },
    { neutral: 'autobús', local: 'buseta' },
    { neutral: 'aguardiente', local: 'guaro' },
  ],
  sensitiveTopics: [
    'Víctimas del conflicto armado, FARC, ELN, paramilitarismo: nada de humor con víctimas.',
    'Falsos positivos: tema delicado, no se ironiza con familias.',
    'Narcotráfico y Pablo Escobar: evitar romantización; sátira al sistema sí, glorificación no.',
    'Líderes sociales asesinados: tono respetuoso.',
    'Desplazamiento forzado: no humor a costa de víctimas.',
  ],
  kickerExamples: [
    'NO JODA',
    'SE ARMÓ LA GORDA',
    'EXCLUSIVA',
    'BOMBAZO',
    'ESCÁNDALO NACIONAL',
    'ALERTA MÁXIMA',
  ],
  headlineExamples: [
    'NO JODA: revelan por qué subió otra vez el pasaje de TransMilenio y los usuarios están que arden',
    'EXCLUSIVA: senador prometió obra que jamás se construyó y ahora todo el país se ríe',
    'BOMBAZO en el Congreso: debate terminó a los gritos por culpa de un café frío',
  ],
  writingRules: [
    'Alternar tuteo bogotano y formas costeñas según tono; "sumercé" en notas más amables.',
    'Léxico colombiano: "plata", "parce", "camello", "rumba", "buseta".',
    'Humor regional: paisa, costeño, rolo; sin caer en estereotipo ofensivo.',
    'Referencias culturales: Congreso, café, fútbol (Selección Colombia), Medellín, Bogotá, Cartagena.',
    'Evitar argentinismos, mexicanismos y españolismos ("che", "órale", "tío", "guay").',
  ],
};
