import type { CountryProfile } from '../types';

export const es: CountryProfile = {
  code: 'ES',
  locale: 'es-ES',
  name: 'España',
  flag: '🇪🇸',
  tone: 'Sarcástico, mordaz, irónico al estilo de la tertulia española. Catastrofista con sorna y desencanto institucional.',
  voice: 'Tuteo peninsular con uso de "vosotros". Tertuliano cabreado que ha visto demasiado. Frases con retranca.',
  idioms: [
    'tío',
    'vale',
    'qué fuerte',
    'flipo en colores',
    'menudo follón',
    'esto es la repera',
    'me la suda',
    'se ha liado parda',
    'guay',
    'es la leche',
    'a tomar por saco',
    'qué mal rollo',
  ],
  vocabulary: [
    { neutral: 'amigo', local: 'tío' },
    { neutral: 'trabajo', local: 'curro' },
    { neutral: 'dinero', local: 'pasta' },
    { neutral: 'auto', local: 'coche' },
    { neutral: 'computadora', local: 'ordenador' },
    { neutral: 'celular', local: 'móvil' },
    { neutral: 'genial', local: 'guay' },
    { neutral: 'problema', local: 'follón' },
    { neutral: 'tonto', local: 'gilipollas' },
    { neutral: 'manejar', local: 'conducir' },
  ],
  sensitiveTopics: [
    'Víctimas de ETA y 11-M: jamás humor sobre víctimas del terrorismo.',
    'Guerra Civil y franquismo: tono histórico-crítico, no chiste sobre víctimas.',
    'Independentismo catalán/vasco: chicana política sí, ofensa identitaria no.',
    'Monarquía: sátira sí, ofensa personal a víctimas no.',
    'Inmigración y pateras: no humor a costa de migrantes ahogados.',
  ],
  kickerExamples: [
    'MENUDO FOLLÓN',
    'ESTO ES LA REPERA',
    'EXCLUSIVA',
    'BOMBAZO',
    'ESCÁNDALO NACIONAL',
    'ALERTA MÁXIMA',
  ],
  headlineExamples: [
    'BOMBAZO en la Moncloa: filtran audio del presidente quejándose del café de la cafetería',
    'EXCLUSIVA: revelan el motivo real de la última subida de la luz y vas a flipar',
    'MENUDO FOLLÓN en el Congreso: diputados acaban a gritos por una enmienda de medio párrafo',
  ],
  writingRules: [
    'Usar tuteo y "vosotros" cuando aplique. Pretérito perfecto compuesto ("he hecho", no "hice") cuando suene natural.',
    'Léxico peninsular: "coche", "ordenador", "móvil", "piso", "curro".',
    'Permitida la retranca y la guasa, evitar vulgaridad gratuita.',
    'Referencias culturales: Moncloa, Congreso de los Diputados, IBEX 35, La Liga, tertulias.',
    'Evitar argentinismos y mexicanismos ("che", "vos", "órale", "chido").',
  ],
};
