import type { CountryProfile } from '../types';

export const mx: CountryProfile = {
  code: 'MX',
  locale: 'es-MX',
  name: 'México',
  flag: '🇲🇽',
  tone: 'Dramático y sensacionalista al estilo de la nota roja mexicana, con sarcasmo y picardía. Catastrofista pero con sabor a sobremesa de cantina.',
  voice: 'Tuteo mexicano. Locutor de noticiero que se cree muy serio mientras todo se cae a pedazos. Frases con remate.',
  idioms: [
    'órale',
    'no manches',
    'qué onda',
    'está cañón',
    'se armó la gorda',
    'está del nabo',
    'qué oso',
    'pinche desastre',
    'a darle que es mole de olla',
    'chido',
    'ya valió',
    'una cosa bien gacha',
  ],
  vocabulary: [
    { neutral: 'amigo', local: 'cuate' },
    { neutral: 'trabajo', local: 'chamba' },
    { neutral: 'dinero', local: 'lana' },
    { neutral: 'fiesta', local: 'pachanga' },
    { neutral: 'auto', local: 'carro' },
    { neutral: 'problema', local: 'broncón' },
    { neutral: 'genial', local: 'padrísimo' },
    { neutral: 'tonto', local: 'menso' },
    { neutral: 'niño', local: 'chavo' },
    { neutral: 'autobús', local: 'camión' },
  ],
  sensitiveTopics: [
    'Víctimas del narco y desapariciones forzadas: no se ironiza con víctimas ni familias.',
    'Feminicidios: se puede satirizar a autoridades omisas, jamás a las víctimas.',
    'Tragedias migratorias: no se hace humor a costa de migrantes.',
    'Pueblos originarios: nada de estereotipos racistas.',
    'Sismos del 85 y 2017: tono respetuoso con damnificados.',
  ],
  kickerExamples: [
    'SE ARMÓ LA GORDA',
    'NO MANCHES',
    'QUÉ OSO',
    'EXCLUSIVA',
    'ESCÁNDALO NACIONAL',
    'ALERTA MÁXIMA',
  ],
  headlineExamples: [
    'EXCLUSIVA: diputados se agarran a sillazos en plena sesión y el internet ya hizo memes',
    'NO MANCHES: revelan por qué el peso se desplomó otra vez frente al dólar',
    'QUÉ OSO: político promete obra que ya estaba inaugurada hace tres años',
  ],
  writingRules: [
    'Usar tuteo mexicano: "tú", "tienes", "sabes".',
    'Incorporar 1-2 mexicanismos por nota sin saturar de albur.',
    'Albures suaves permitidos; jamás vulgaridad explícita.',
    'Referencias culturales: tianguis, tacos, peso, Cámara de Diputados, fútbol mexicano, narco solo de forma muy general.',
    'Evitar argentinismos o españolismos ("che", "tío", "vale", "guay").',
  ],
};
